trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Install PHP and necessary extensions
    sudo apt-get update
    sudo apt-get install -y php7.4

    echo Install Composer
    sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

    echo Install project dependencies
    cd $(Build.SourcesDirectory)
    sudo composer install

    echo Run PHP tests
    phpunit --configuration phpunit.xml

    echo Deploy PHP website
    # Add your deployment commands here
    # For example, copying files to a web server or deploying to Azure Web Apps
  displayName: 'Build, Test, and Deploy PHP Website'
